### ISSUE TITLE
Зачіска

### ISSUE THREAD

**Issue by Natalia1565** [Tysia1698/Tysia16#11]
не повністю підібрана, з локонами)

**Comment by Tysia1698** [comment]
тааа

**Comment by Natalia1565** [comment]
давай спочатку підберем зачіску для нареченої)

**Comment by Tysia1698** [comment]
http://ogo.ua/images/articles/1567/big/1440017608.jpeg
пасуватиме мені??

**Comment by Natalia1565** [comment]
мені 2 дуже подобається, я таку на випускний хотіла робити)

**Comment by Tysia1698** [comment]
ну мені вона також подобається)

**Comment by Tysia1698** [comment]
давай тепер виберемо для дружок

**Comment by Natalia1565** [comment]
тоді давай тепер для дружок)

**Comment by Tysia1698** [comment]
ти особисто яку б хотіла??

**Comment by Natalia1565** [comment]
http://xtrend.pp.ua/modni-vechirni-zachiski-z-pokrokovimi-foto-5-trendovix-variantiv/

**Comment by Natalia1565** [comment]
оця 2 мені подобається

**Comment by Natalia1565** [comment]
що скажеш?

**Comment by Natalia1565** [comment]
https://idei-dekoru.com/2017/06/17/%D0%B2%D0%B5%D1%87%D1%96%D1%80%D0%BD%D1%96-%D0%B7%D0%B0%D1%87%D1%96%D1%81%D0%BA%D0%B8-%D1%86%D1%96%D0%BA%D0%B0%D0%B2%D1%96-%D1%96%D0%B4%D0%B5%D1%97-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%BE%D0%BB%D0%BE%D1%81/

**Comment by Natalia1565** [comment]
а теж непогана, якщо піднята

**Comment by Tysia1698** [comment]
гарно варіант перший,що ти кидала

**Comment by Natalia1565** [comment]
тоді виришіли, можна ще додати якигось живих квітів у волосся)

**Comment by Tysia1698** [comment]
кльова ідея)

**Comment by Natalia1565** [comment]
https://topwedding.com.ua/winter-wedding-hairstyles/
або таке)

**Comment by Natalia1565** [comment]
ахахах

**Comment by Natalia1565** [comment]
можна щось поєднати)

**Comment by Tysia1698** [comment]
ахахха, давай , коли підемо на пробні варіанти тоді спробуємо)

**Comment by Natalia1565** [comment]
добре)
