### ISSUE TITLE
Плаття для дружок

### ISSUE THREAD

**Issue by Natalia1565** [Tysia1698/Tysia16#12]
світло рожевого або бузкового кольору)

**Comment by Natalia1565** [comment]
як думаєш краще довгі чи короткі?)

**Comment by Tysia1698** [comment]
я б хотіла, що би ви мали довгі, але з вирізом на нозі

**Comment by Natalia1565** [comment]
супер)

**Comment by Natalia1565** [comment]
https://shafa.ua/women/platya/maksi/7622020-plattya-dlya-druzhok

**Comment by Natalia1565** [comment]
такого типу)

**Comment by Tysia1698** [comment]
мені надзвичайно подобаються

**Comment by Natalia1565** [comment]
будем шити чи купувати?

**Comment by Tysia1698** [comment]
напевно шити, адже друга дружка немає такого розміру як ти

**Comment by Natalia1565** [comment]
тоді супер) одна може бути в світло рожевому, а інша в світло фіолетовому)

**Comment by Tysia1698** [comment]
ооо так, типу як перша дружка, тобто головна і друга

**Comment by Tysia1698** [comment]
вирішили)

**Comment by Natalia1565** [comment]
ну так, тоді домовилися)
