### ISSUE TITLE
Вибір відео-оператора та фотографа

### ISSUE THREAD

**Issue by Tysia1698** [Tysia1698/Tysia16#13]
Хороший і професійний

**Comment by Tysia1698** [comment]
маєш когось зі знайомих?

**Comment by Natalia1565** [comment]
маю, але вони мені не сподобалися, тому треба когось шукати(

**Comment by Tysia1698** [comment]
ого, ясно

**Comment by Tysia1698** [comment]
Маю знайомого фотографа, візьме приблизно 1000 гривень

**Comment by Tysia1698** [comment]
але це без обробки

**Comment by Tysia1698** [comment]
не знаю чи це дорого чи ні

**Comment by Natalia1565** [comment]
ооо це дуже дешево к для весілля) я теж за фотографа згадала, він бере дорожче, але фото гарні)

**Comment by Tysia1698** [comment]
а відео-оператор 800$

**Comment by Natalia1565** [comment]
https://girko.net/lviv/video/?from=adwords_video_lviv&gclid=CjwKCAjwq_vWBRACEiwAEReprCuJxPAXcqDc7FmeELAHOgGju5a4An8AxZWYkJx03ZQTBXEd74VYWRoCy7cQAvD_BwE

**Comment by Natalia1565** [comment]
тут є різні, можна дзвонити і питати, одразу дивитися на роботу)

**Comment by Tysia1698** [comment]
давай у суботу зустрінемося?)

**Comment by Natalia1565** [comment]
https://girko.net/profile/6494/

**Comment by Tysia1698** [comment]
і буде обдзвонювати?

**Comment by Natalia1565** [comment]
тут є фото і відео разом)

**Comment by Tysia1698** [comment]
будемо

**Comment by Tysia1698** [comment]
ооой

**Comment by Natalia1565** [comment]
добре, я можу, але десь до обіду було б краще

**Comment by Tysia1698** [comment]
клас, мені подобається

**Comment by Tysia1698** [comment]
добре)

**Comment by Natalia1565** [comment]
ти закрила вже?
