### ISSUE TITLE
Вибрати ді-джея

### ISSUE THREAD

**Issue by Tysia1698** [Tysia1698/Tysia16#5]
сучасного і не дорогого

**Comment by Natalia1565** [comment]
ти хочеш лише данс-музику?

**Comment by Natalia1565** [comment]
бо якщо будуть старші люди, то треба ще щось для них вибрати +
 конкурси)

**Comment by Tysia1698** [comment]
Не тільки, напевно щось і ліричне , щоб був перший танець під Ed Sheeran

**Comment by Tysia1698** [comment]
ну можна ж мікс зробити

**Comment by Tysia1698** [comment]
наприклад, 5 пісень наших, 5 пісень для дорослих і так міксувати

**Comment by Natalia1565** [comment]
ну так, але щоб увесь двіж був за допомогою джіджея

**Comment by Natalia1565** [comment]
ну да, та навіть можна менше для дорослих

**Comment by Natalia1565** [comment]
ще треба щоб вони конкурси створювали)

**Comment by Tysia1698** [comment]
Ой, та чуєш під " А на теплоходе музика играет" можна ще більше веселитися ніж під наші сучасні

**Comment by Natalia1565** [comment]
ну да, погоджуюся)

**Comment by Tysia1698** [comment]
Чекааааай!!! Нам потрібно дописати,що вибір тамади потрібно, давай Заліска?

**Comment by Natalia1565** [comment]
то хто?

**Comment by Natalia1565** [comment]
може Притулу?

**Comment by Tysia1698** [comment]
Відомий Блогер у Чернівцях, він дуже кльовий і веселий і не дорого бере

**Comment by Natalia1565** [comment]
зараз загуглю

**Comment by Natalia1565** [comment]
добре, мені подобається, давай, буде весело)))))

**Comment by Tysia1698** [comment]
Хочеш познайомитися? ахаххаах

**Comment by Natalia1565** [comment]
ахахха так як буду в тебе дружкою, то познайомлюся)))

**Comment by Tysia1698** [comment]
а хто казав,що ти дружка? ахахаха

**Comment by Natalia1565** [comment]
я не понялаЯ, ахахах, так чого я тут сиджу і з тобою парюся нарахунок джі-джея?)

**Comment by Tysia1698** [comment]
ахахахах..жарт

**Comment by Natalia1565** [comment]
ти так не жартуй)

**Comment by Tysia1698** [comment]
Все,давай до діла) Ми вирішили на рахунок ді-джея)

**Comment by Natalia1565** [comment]
окей)
