### ISSUE TITLE
вибір місця проведення

### ISSUE THREAD

**Issue by Natalia1565** [Tysia1698/Tysia16#6]
просторне і затишне

**Comment by Tysia1698** [comment]
Чесно, не маю ідей, не знаю , де у Львові гарно, що порадиш?

**Comment by Natalia1565** [comment]
я б порадила десь за містом, там зазвичай просторініше і багатше)

**Comment by Tysia1698** [comment]
Так, чудова ідея!

**Comment by Tysia1698** [comment]
Бюджет не головний)

**Comment by Natalia1565** [comment]
http://wedding.ua/images_user/banket/banket-decorating.jpg

**Comment by Natalia1565** [comment]
як тобі?

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwj1sOetzdLaAhUGhqYKHdYmCsgQjRx6BAgAEAU&url=http%3A%2F%2Fkupidon.if.ua%2Fvesilna-moda%2Fpopulyarni-mistsya-dlya-provedennya-vesillya-v-2016-rotsi&psig=AOvVaw1zHM44wgjbz_CxddDGjS4W&ust=1524648614540152

**Comment by Tysia1698** [comment]
ЧУУУУУДООООВОО!! Другий варіант мені надзвичайноо подобається!

**Comment by Natalia1565** [comment]
мені теж)))
