### ISSUE TITLE
місце проведення весільної церемонії

### ISSUE THREAD

**Issue by Tysia1698** [Tysia1698/Tysia16#7]
Виїздна церемонія

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwimyp-XztLaAhUDiSwKHYvkBpcQjRx6BAgAEAU&url=https%3A%2F%2Fjoinuplviv.com%2Forganizacija-vesillja-na-maldivah%2F&psig=AOvVaw1GUrZ4AEn6xoGNEVFKWOT7&ust=1524648948671249

**Comment by Natalia1565** [comment]
ти хочеш в лісі, парку, морі?

**Comment by Tysia1698** [comment]
Парк або море.

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjTgOaoztLaAhVBHiwKHb0cA1QQjRx6BAgAEAU&url=http%3A%2F%2Fwedding-empire.lviv.ua%2Fviyizna-tseremoniya%2F&psig=AOvVaw1GUrZ4AEn6xoGNEVFKWOT7&ust=1524648948671249

**Comment by Natalia1565** [comment]
ну от є два зображення

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiHqv60ztLaAhWGjCwKHRSEB4QQjRx6BAgAEAU&url=http%3A%2F%2Fporadatour.com.ua%2Fauxpage_vesilna-ceremonija-v-mexica%2F&psig=AOvVaw1GUrZ4AEn6xoGNEVFKWOT7&ust=1524648948671249

**Comment by Natalia1565** [comment]
ти хочеш весільну церемонію в той же день як саме весілля?

**Comment by Tysia1698** [comment]
Звісно

**Comment by Natalia1565** [comment]
ну тоді треба в парку або в лісі, бо до моря не доїдеш

**Comment by Tysia1698** [comment]
Але я хочу у Львові, а не закордоном

**Comment by Tysia1698** [comment]
В лісі ні, я боюсь всяких комах

**Comment by Natalia1565** [comment]
ахахах та ще всіх комарі покусають, давай в парку)

**Comment by Tysia1698** [comment]
Ну от

**Comment by Natalia1565** [comment]
можна в ботанічному саді)

**Comment by Tysia1698** [comment]
Для чого мені цей ботанічний сад

**Comment by Natalia1565** [comment]
або на березі якогось озера)

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiIj7eYz9LaAhUEiywKHSnMD54QjRx6BAgAEAU&url=http%3A%2F%2Fwww.rivne1.tv%2FInfo%2F%3Fid%3D54000&psig=AOvVaw1GUrZ4AEn6xoGNEVFKWOT7&ust=1524648948671249

**Comment by Tysia1698** [comment]
Щоб голову задурманив? Щоб замість того , щоб я казала так, я дивилася на рослини? ахахаха

**Comment by Tysia1698** [comment]
ага, біля озера, щоб ящірки або жаби мені під платтям скакали

**Comment by Tysia1698** [comment]
дякую!

**Comment by Natalia1565** [comment]
добре, не нервуйся, тоді де? в якомусь парку?

**Comment by Tysia1698** [comment]
ахаххаха

**Comment by Tysia1698** [comment]
так

**Comment by Natalia1565** [comment]
як тобі осстаннє фото?

**Comment by Tysia1698** [comment]
Можливо Стрийський?

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjmh-7Zz9LaAhXJdCwKHQitDLEQjRx6BAgAEAU&url=https%3A%2F%2Fwed.in.ua%2Fuk%2Fblog%2Fviyizna-tseremoniya-test&psig=AOvVaw1FXEoc3GtazRaWz9FjrEB5&ust=1524649357809839

**Comment by Tysia1698** [comment]
Так, мені подобається!
