### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by Natalia1565** [Tysia1698/Tysia16#8]
бенкетне, вишукане

**Comment by Tysia1698** [comment]
Але не дуже жирне та шкідлива

**Comment by Tysia1698** [comment]
щось легке , тому що це літо і так ніхто їсти не захоче

**Comment by Natalia1565** [comment]
я підтримую, +щогб столи не ломилися від страв, бо це не естетично

**Comment by Tysia1698** [comment]
але і щоб кількість була достатня, адже гостей +- 100

**Comment by Natalia1565** [comment]
також можна це зробити фуршет, крім того коли люди просто сидять і їдять, наприклад, на напої, солодке, фрукти тощо?

**Comment by Tysia1698** [comment]
Так, це крута ідея

**Comment by Natalia1565** [comment]
ти хочеш традиційну кухню чи більше європейську?

**Comment by Tysia1698** [comment]
ніяких свинок і т.д. Хочу європейську і щоб можливо також були морепродукти

**Comment by Tysia1698** [comment]
https://i.pinimg.com/originals/40/ce/af/40ceaf83d5534a903541d830e969c609.jpg
 
наприклад щось таке?

**Comment by Tysia1698** [comment]
як тобі ідея?

**Comment by Tysia1698** [comment]
https://i0.wp.com/topwedding.com.ua/wp-content/uploads/2015/04/%D0%A1%D0%BA%D0%BB%D0%B0%D0%B4%D0%B0%D1%94%D0%BC%D0%BE-%D0%B2%D0%B5%D1%81%D1%96%D0%BB%D1%8C%D0%BD%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E-5-%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%96%D0%B2-4.jpg?resize=696%2C385&ssl=1


А солодке ось таке

**Comment by Natalia1565** [comment]
так мені подобається, треба їхати в ресторан і узгоджувати, можу поїхати з тобою і допомогти)

**Comment by Tysia1698** [comment]
Давай о 13:00 завтра!

**Comment by Natalia1565** [comment]
добре)
