### ISSUE TITLE
Декорація залу

### ISSUE THREAD

**Issue by Natalia1565** [Tysia1698/Tysia16#9]
лише живі квіти і в тон весілля

**Comment by Natalia1565** [comment]
а який колір весілля?

**Comment by Tysia1698** [comment]
так, я хочу піони

**Comment by Tysia1698** [comment]
олір весілля біло-рожевий, біло-пурпуровий

**Comment by Tysia1698** [comment]
колір*

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjr6s3T0dLaAhXDDiwKHdEwCiwQjRx6BAgAEAU&url=https%3A%2F%2Fwedlemon.com.ua%2Fnews%2FOformlennya_zalu_na_vesillya.html&psig=AOvVaw0WDiGFs_aIjF3gwWR0tPgF&ust=1524649902686536

**Comment by Tysia1698** [comment]
або ж замість піонів - бузок

**Comment by Natalia1565** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwibzZfo0dLaAhUKBSwKHQYeCVEQjRx6BAgAEAU&url=http%3A%2F%2Fflowershop.0312.ua%2Fpage%2Fvse-dlja-vesillja&psig=AOvVaw0WDiGFs_aIjF3gwWR0tPgF&ust=1524649902686536

**Comment by Tysia1698** [comment]
чудово, мені подобається

**Comment by Tysia1698** [comment]
де взяти стільки бузку?

**Comment by Natalia1565** [comment]
та є спеціальні агенції по прикрашанню залу і машин, це вже буде їхня проблема

**Comment by Natalia1565** [comment]
а машини ти які хочеш?)

**Comment by Tysia1698** [comment]
https://avatars.mds.yandex.net/get-pdb/27625/884bcd00-9784-4bea-a56a-72403b6783a3/s800

**Comment by Tysia1698** [comment]
https://avatars.mds.yandex.net/get-pdb/27625/884bcd00-9784-4bea-a56a-72403b6783a3/s800

**Comment by Natalia1565** [comment]
може трохи ще білого додати в букет?)

**Comment by Tysia1698** [comment]
який тобі більше подобається?

**Comment by Natalia1565** [comment]
ну другий кращий

**Comment by Tysia1698** [comment]
Хочу білі Land Rover Range Rover

**Comment by Tysia1698** [comment]
https://infomisto.info/gp/d/6/8/7/ff00dfd243a0b6e6990d3e023e35/bz5sghks9w6c/w600h900.jpg
ось така декорація на машину нареченого і на кштал цього зробити для нареченої

**Comment by Tysia1698** [comment]
як тобі?

**Comment by Natalia1565** [comment]
мені подобається)
